#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    mini = arr.copy()
    maxi = arr.copy()
    maximum = 0
    minimum = 0
    for i in range(4):
        b = max(maxi)
        a = min(mini)
        maximum = maximum + b
        minimum = minimum + a
        maxi.remove(b)
        mini.remove(a)
    print(minimum,maximum)
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
