#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    # Write your code here
    s = 0
    for i in n:
        j = int(i)
        s = s +(j*k)
    r = 0
    arr = []
    arr.append(s)
    while(arr[len(arr)-1]//10 >0):
        x = arr[len(arr)-1]
        while(x > 0):
            r = r + x%10
            x = x //10
        arr.append(r)
        r = 0
    
    return arr[len(arr)-1]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()
